export const homePageInfo = [
  {
    'title': 'Banners',
    'key': 'banner',
    'list': [
      { 'content_id': 1001, 'publish_time': '2016', 'title': 'John Wick 3', 'orentitation': 0, 'duration': '40 minutes', 'banner_medium': '', 'banner_image': 'John_wick.jpeg', 'poster_image': 'john_wick_poster.png', 'description': 'John Wick is on the run after killing a member of the international assassins guild, and with a $14 million price tag on his head, he is the target of hit men and women everywhere.' , 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1002, 'publish_time': '2019', 'title': 'The Handmaiden', 'orentitation': 0, 'duration': '90 minutes', 'banner_medium': '', 'banner_image': 'Handmaiden.jpeg', 'poster_image': 'handmaiden_poster.png', 'description': '', 'playback_url': '', 'tags': 'Thriller & Misdaad, Drama, Romantiek' }]
  },
  {
    'title': 'Movies',
    'key': 'movies',
    'list': [
      { 'content_id': 1008, 'description': 'A troubled security guard begins working at Freddy Fazbears Pizza During his first night on the job, he realizes that the night shift wont be so easy to get through. Pretty soon he will unveil what actually happened at Freddys','duration': '40 minutes', 'publish_time': '2019', 'title': 'FIVE NIGHTS AT FREDDYS' , 'orentitation': 1, 'banner_medium': 'cae23eedba1c8c08b57ebc9e893879c419f4d4e9.jpg', 'banner_image': 'five_nights.jpeg', 'poster_image': 'poster_4.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1009, 'description': 'The incredible true story of a former government agent turned vigilante who embarks on a dangerous mission to rescue hundreds of children from traffickers.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'SOUND OF FREEDOM', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'sound_freedom.jpg', 'poster_image': 'poster_5.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1010, 'description': 'The history of the United States from the 1950s to the 70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'Forrest Gump', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'forest_gump.jpg', 'poster_image': 'poster_6.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1011, 'description': 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'PULP FICTION', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'pulp_fiction.jpeg', 'poster_image': 'poster_7.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1012, 'description': 'An alien scarab chooses Jaime Reyes to be its symbiotic host, bestowing the recent college graduate with a suit of armor thats capable of extraordinary powers, forever changing his destiny as he becomes the superhero known as Blue Beetle.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'Blue Beetle', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'Blue_beetle.jpeg', 'poster_image': 'poster_8.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1013, 'description': 'During the 90s, a new faction of Transformers - the Maximals - join the Autobots as allies in the battle for Earth.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'TRANSFORMERS: RISE OF THE BEASTS', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'Transformers.jpg', 'poster_image': 'poster_9.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1014, 'description': 'Barbie suffers a crisis that leads her to question her world and her existence.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'Barbie', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'Barbie.jpeg', 'poster_image': 'poster_10.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1015, 'description': 'When two girls disappear into the woods and return three days later with no memory of what happened to them, the father of one girl seeks out Chris MacNeil, whos been forever altered by what happened to her daughter fifty years ago.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'THE EXORCIST BELIEVER', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'Exorcist.jpeg', 'poster_image': 'poster_11.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1016, 'description': 'Dom Toretto and his family are targeted by the vengeful son of drug kingpin Hernan Reyes.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'FAST-X', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'FastX.jpeg', 'poster_image': 'poster_12.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1017, 'description': 'Robert McCall finds himself at home in Southern Italy but he discovers his friends are under the control of local crime bosses. As events turn deadly, McCall knows what he has to do: become his friends protector by taking on the mafia.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'THE Equalizer-3', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'equalizer_3.jpeg', 'poster_image': 'poster_13.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1018, 'description': 'A sick and desperate John travels to Mexico for a risky and experimental medical procedure in hopes of a miracle cure for his cancer only to discover the entire operation is a scam to defraud the most vulnerable.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'SAW X', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'saw_x.jpeg', 'poster_image': 'poster_14.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1019, 'description': 'The adventures of a band of space warriors who work to protect the universe from the evil overlord Thanos.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'Gardians of the Galaxy', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'guardians_galaxy.webp', 'poster_image': 'poster_1.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1020, 'description': 'Ethan Hunt and his IMF team must track down a dangerous weapon before it falls into the wrong hands.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'MISSION:IMPOSSIBLE Dead Reckoning -Part ONE', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'mission_imposisble.jpeg', 'poster_image': 'poster_2.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1021, 'description': 'Armed with every weapon they can get their hands on, the Expendables are the worlds last line of defense and the team that gets called when all other options are off the table.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'EXPENDABLES-4', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'expen4bles.jpeg', 'poster_image': 'poster_3.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1022, 'description': 'A troubled security guard begins working at Freddy Fazbears Pizza During his first night on the job, he realizes that the night shift wont be so easy to get through. Pretty soon he will unveil what actually happened at Freddys' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'FIVE NIGHTS AT FREDDYS', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'five_nights.jpeg', 'poster_image': 'poster_4.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1023, 'description': 'The incredible true story of a former government agent turned vigilante who embarks on a dangerous mission to rescue hundreds of children from traffickers.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'SOUND OF FREEDOM', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'sound_freedom.jpg', 'poster_image': 'poster_5.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1024, 'description': 'The history of the United States from the 1950s to the 70s unfolds from the perspective of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'Forrest Gump', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'forest_gump.jpg', 'poster_image': 'poster_6.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' },
      { 'content_id': 1025, 'description': 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'PULP FICTION', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'pulp_fiction.jpeg', 'poster_image': 'poster_7.webp', 'playback_url': '', 'tags': 'Thriller & Crime,Drama' }
    ]
  },
  {
    'title': 'Comedy',
    'key': 'comedy',
    'list': [
      { 'content_id': 1026, 'description': 'A charismatic but clueless news anchor faces challenges when a talented female journalist joins the newsroom.','duration': '40 minutes', 'publish_time': '2019', 'title': 'Anchorman: The Legend of Ron Burgundy', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'anchorman_banner.jpeg', 'poster_image': 'anchorman_poster.jpeg', 'playback_url': '', 'tags': 'comedy' },
      { 'content_id': 1027, 'description': 'A student decides to skip school for a day of adventure, outsmarting authority figures and creating a memorable day off.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': "Ferris Bueller's Day Off", 'orentitation': 1, 'banner_medium': '', 'banner_image': 'ferrisbuellersdayoff_banner.jpeg', 'poster_image': 'ferrisbuellersdayoff_poster.jpeg', 'playback_url': '', 'tags': 'comedy' },
      { 'content_id': 1028, 'description': 'Two friends embark on a cross-country trip, encountering absurd and humorous situations.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'Dumb and Dumber', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'dumbanddumber_banner.jpeg', 'poster_image': 'dumbanddumber_poster.jpeg', 'playback_url': '', 'tags': 'comedy' },
      { 'content_id': 1029, 'description': 'A quirky film follows the misadventures of a hotel concierge and his protégé involving a valuable painting and a murder.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'The Grand Budapest Hotel', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'thegrandbudapesthotel_banner.jpeg', 'poster_image': 'thegrandbudapesthotel_poster.jpeg', 'playback_url': '', 'tags': 'comedy' },
      { 'content_id': 1030, 'description': 'A group of paranormal investigators forms the Ghostbusters to save New York City from supernatural threats, blending comedy and supernatural elements.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'Ghostbusters', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'ghostbusters_banner.jpeg', 'poster_image': 'ghostbusters_poster.jpeg', 'playback_url': '', 'tags': 'comedy' },
      { 'content_id': 1031, 'description': 'A parody of disaster films, the movie follows a mismatched crew trying to safely land a troubled flight.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'Airplane!', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'airplane_banner.jpeg', 'poster_image': 'airplane_poster.jpeg', 'playback_url': '', 'tags': 'comedy' },
      { 'content_id': 1032, 'description': 'An animated comedy filled with humor and creativity as an ordinary LEGO construction worker becomes the key to saving the world.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'The LEGO Movie', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'thelegomovie_banner.jpeg', 'poster_image': 'thelegomovie_poster.jpeg', 'playback_url': '', 'tags': 'comedy' },
      { 'content_id': 1033, 'description': "A man's teddy bear comes to life, causing comedic chaos as they navigate adult life together." , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'Ted', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'ted_banner.jpeg', 'poster_image': 'ted_poster.jpeg', 'playback_url': '', 'tags': 'comedy' },
      { 'content_id': 1034, 'description': 'A man becomes embroiled in a kidnapping plot after being mistaken for a millionaire with the same name, leading to a quirky and comedic odyssey.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'The Big Lebowski', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'thebiglebowski_banner.jpeg', 'poster_image': 'thebiglebowski_poster.jpeg', 'playback_url': '', 'tags': 'comedy' },
      { 'content_id': 1035, 'description': 'A dim-witted male model becomes entangled in a plot to assassinate the Prime Minister, leading to absurd and comedic situations.' , 'duration': '40 minutes', 'publish_time': '2019', 'title': 'Zoolander', 'orentitation': 1, 'banner_medium': '', 'banner_image': 'zoolander_banner.jpeg', 'poster_image': 'zoolander_poster.jpeg', 'playback_url': '', 'tags': 'comedy' }
    ]
  },
  {
    'title': 'News',
    'key': 'news',
    'list': [
      { 'content_id': 1003, 'description': "A television network cynically exploits a deranged former anchor's ravings and revelations about the news media for its own profit, but finds that his message may be difficult to control.", 'publish_time': '2019', 'title': 'Network', 'orentitation': 1, 'duration': '50 minutes', 'banner_medium': '', 'banner_image': 'network_banner.jpeg', 'poster_image': 'network_poster.jpeg', 'playback_url': '', 'tags': 'News' },
      { 'content_id': 1004, 'description': "The Washington Post reporters Bob Woodward and Carl Bernstein uncover the details of the Watergate scandal that leads to President Richard Nixon's resignation.", 'publish_time': '2021', 'title': "All the President's Men ", 'orentitation': 1, 'duration': '65 minutes', 'banner_medium': '', 'banner_image': 'atpm_poster.jpeg', 'poster_image': 'atpm_banner.jpeg', 'playback_url': '', 'tags': 'News' },
      { 'content_id': 1005, 'description': 'Journalist witness a nuckear power plant accident and find their attempts to expose it thwarted', 'publish_time': '2022', 'title': 'The China Syndrome', 'orentitation': 1, 'duration': '30 minutes', 'banner_medium': '', 'banner_image': 'tcs_banner.jpeg', 'poster_image': 'tcs_banner.jpeg', 'playback_url': '', 'tags': 'News' },
      { 'content_id': 1006, 'description': "A journalist is trapped in Cambodia during tyrant Pol Pot's bloody 'Year Zero' cleansing campaign, which claimed the lives of two million 'undesirable' civilians.", 'publish_time': '2020', 'title': 'The Killing Fields', 'orentitation': 1, 'duration': '80 minutes', 'banner_medium': '', 'banner_image': 'tkf_banner.jpeg', 'poster_image': 'tkf_poster.jpeg', 'playback_url': '', 'tags': 'News' },
      { 'content_id': 1007, 'description': 'A research chemist comes under personal and professional attack when he decides to appear in a 60 Minutes exposé on Big Tobacco.', 'publish_time': '2021', 'title': 'The Insider', 'orentitation': 1, 'duration': '90 minutes', 'banner_medium': '', 'banner_image': 'tinsider_banner.jpeg', 'poster_image': 'tinsider_poster.jpeg', 'playback_url': '', 'tags': 'News' },
    ]
  }
]

export const categories = [
    { 'content_id': 1, 'category_id': '01', 'title': 'Home', 'slug': 'home', 'icon': 'images/home.png', 'title_en': 'Home', },
    { 'content_id': 1, 'category_id': '01', 'title': 'Search', 'slug': 'search', 'icon': 'images/search.png', 'title_en': 'Search', },
    { 'content_id': 1, 'category_id': '01', 'title': 'Movies', 'slug': 'movies', 'icon': 'images/movies.png', 'title_en': 'Movies', },
    { 'content_id': 1, 'category_id': '01', 'title': 'Profile', 'slug': 'profile', 'icon': 'images/user.png', 'title_en': 'Profile', }
]
